name: Node.js Veracode Upload & Scan

on:
  workflow_dispatch:
  push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_scan:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [12.x, 14.x, 16.x]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
 
    - name: Run Veracode SCA
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
        curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan --allow-dirty --update-advisor
